services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      PORT: 3000
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
      - ./test:/app/test:ro
    command: npm run dev
